#!/bin/sh

dir="$HOME/.scripts"

cd $dir
git fetch
git pull origin $(git rev-parse --abbrev-ref HEAD)

cd $dir/bin
ls -Ad $dir/folders | \
xargs -I{} find {} -type f | \
xargs -I{} ln -s {} 2>/dev/null

exit 0
