#!/bin/sh

usage() {
cat << EOF
usage: scripts <command>

These are common Scripts commands used in various situations:

  - update  Update all scripts
  - clear   Remove all symbolized scripts 
  - list    Show scripts

EOF
}

case $1 in 
    update) scripts-update ;; 
    clear) echo "clear command is not implemented." ;;
    list) ls -1 $(dirname $0);;
    *) usage ;;
esac 
