#!/bin/sh

basedir=~/git

usage() {
    cat << EOF
usage: github clone <url>
EOF
}

[ ! -n "$1" ] && usage

url=$1

if expr "$1" : "https://github.com/" > /dev/null; then
    dir=$(echo ${url#https://github.com/})
elif expr "$1" : "git@github.com:" > /dev/null; then
    dir=$(echo ${url#git@github.com:})
else
    echo "URL is invalid"
    exit 1
fi
dir=$(echo ${dir%.git})
user=$(echo ${dir%%/*})
repo=$(echo ${dir##*/})

mkdir -p $basedir/$user
cd $basedir/$user
git clone $1

cat << EOF

$basedir/$user/$repo
EOF
